### ISSUE TITLE
Question: is it important to disable analytics during compilation?

### ISSUE THREAD

**Issue by tchajed** [uwplse/coq-change-analytics#35]
I use a custom Makefile that doesn't build with `-q`, so the analytics plugin will be loaded during compilation as well as during interactive usage.

Is this bad for your data? If so, I can disable loading the rcfile in my various Makefiles. I'd sort of prefer to do so anyway since it would speed things up a bit.

**Comment by tlringer** [comment]
Thanks for asking! We would like for it to be loaded during compilation, since that means that we can replay data with dependencies for analysis later (to check, for example, how often tactics fail). 

How significant of a slowdown do you experience? We tried to make sure that it only sends the data to the server in large batches, but I can imagine that logging before doing that might be slow.

**Comment by tchajed** [comment]
Ok, it's not "a bit", it's actually really bad:

`time make test` on https://github.com/tchajed/coq-sep-logic reports:

```
# with analytics
      199.62 real        10.71 user         2.94 sys
# without
        8.35 real         6.17 user         2.06 sys
```

The bizarre things is how much time it spends sleeping or blocking - it only does 14s of work in 200s of real time.

On [coq-stdpp](https://gitlab.mpi-sws.org/iris/stdpp) there's a similar extreme slowdown on `theories/base.v` (I didn't wait long enough for it to finish).

**Comment by tlringer** [comment]
Interesting, thanks for pointing this out. I'll take a look today. I wonder
if batching only works in coqtop for some reason. I'll take a look, but for
the sake of beta if this blocks development a lot you can disable it
temporarily for compilation if you need to since we won't use your data
eventually anyways. But we'd prefer you don't so we can run some tests on
how to analyze data and determine if we need more.

Nonetheless this seems very important to fix before prod, so thanks for
reporting this.

**Comment by tlringer** [comment]
Indeed, it looks like when you run coqc it runs the `exec` hook on every single line one at a time, so the plugin is sending it line by line to the server, and it's no wonder it's exceptionally slow.

I'm going to add some kind of last sent flag for now so that it doesn't send every few milliseconds, at least, and then I'll think of a more permanent solution for the prod release if need be.

**Comment by tlringer** [comment]
I've pushed updated client code. Please pull to update the client and try again, and let me know if it works OK for you.

**Comment by tlringer** [comment]
Resolving, reopen if issue persists

**Comment by tchajed** [comment]
Compilation times are much better now, thanks!
