### ISSUE TITLE
Replay script does not scale

### ISSUE THREAD

**Issue by tlringer** [uwplse/coq-change-analytics#37]

**Comment by HazardousPeach** [comment]
Commits d9dfc0c is a pretty complete rewrite of the replay.py script.

It uses the original log file format, but reads it in three phases:
So I pushed a new replay script that scales better
The way it does it is, now it defaults to making three passes over the file:
In the first pass, it builds a set of users,
then it asks you to selecte a user, and makes a pass building a set of sessions
then you select a session, and it makes a pass gathering the commands for that session,
and finally displays them
Each pass over the file takes approximately 30 seconds
This is obviously slower than ideal
But already shows us a few things about the data
Foremost in my mind is that, we only have 3 user ids
Since the first two are you and me (probably), that means that only one users data got through to us, or they somehow got merged user ids
There are 3983 sessions under user 1, as opposed to 125 sessions for user 2, and 106 for user 3, so I'm guessing a lot of our users got registered as user 1 somehow
In terms of making the replay faster, I think the best move is probably to give each user their own logfile. This way we can list users with just ls, and then just read the userfile for sessions. Assuming the user 1 thing is a bunch of users combined, I'm guessing this will make the time to pass over each file closer to 1-3 seconds, which seems reasonable, and possibly will allow us to just store an entire users data in memory at once, allowing more complicated queries without multiple passes.

**Comment by HazardousPeach** [comment]
For production, I think we'll want to change the logfile format a bit to make replaying/choosing sessions faster.

My recommendation is to give each user their own logfile. This way we can list users with just `ls`, and then just read the userfile for sessions. I'm guessing this will make the time to pass over each file closer to 1-3 seconds, which seems reasonable, and possibly will allow us to just store an entire users data in memory at once, allowing more complicated queries without multiple passes.

**Comment by HazardousPeach** [comment]
I'm assigning this to @tlringer temporarily for comments on the new logfile format proposal

**Comment by tlringer** [comment]
Sorry for the delay! In between the summit and camping with Misha :)

I think the current format sounds good to me. Do you think this will still be too slow for production? I am reluctant to make major functionality changes (like which file we log to) before production because then we risk introducing new bugs that we didn't have a chance to test in Beta. So I'd prefer to confine changes to the replay process, but if that will absolutely not scale then I am OK making logfile changes.

**Comment by tlringer** [comment]
After discussion, you should do this change since we need it for scalability, but we should make sure to test this with several fake users before prod.

**Comment by tlringer** [comment]
I think we can close this now.
