### ISSUE TITLE
Most Users Getting Merged into User "1"

### ISSUE THREAD

**Issue by HazardousPeach** [uwplse/coq-change-analytics#38]
Based on the data from the beta, it appears that most users are getting merged into the user "1", since there are 3983 sessions under user 1, and only 125 and 106 for users 2 and 3 respectively.

**Comment by tlringer** [comment]
To be honest, I wouldn't be sure if this were the actual data, since one user was an especially heavy user with a very large dependency for his project. Do you know what counts as a single "session"? If it is each file when you compile, 3983 in 2 weeks isn't unreasonable at all

**Comment by tlringer** [comment]
Needs more investigation; will look at this when we look at beta data this upcoming week

**Comment by tlringer** [comment]
We should also check what constitutes a "session"

**Comment by tlringer** [comment]
It looks like there are many short sessions. I'm going to check the code to see when it defines a new session. I suspect the current definition is not useful.

**Comment by tlringer** [comment]
I think, also, when it compiles, that each file is a session.

**Comment by tlringer** [comment]
Yeah, there is one session per file when compilation happens. This is maybe not a huge deal; it makes it really clear what compilation looks like, since you see many sessions a few seconds apart. It's also very, very hard to fix.

But I think that user is a single user, who just had a lot of dependencies.

We will need to make sure, though, to notify beta testers and make sure that everyone removes their dependency on the plugin and their .analytics_profile before we delete the data and move to the next stage.
